-- ==============================================================================
-- КАТАЛОГ ПРО (CATALOG PRO) - SUPABASE ӨГӨГДЛИЙН САНГИЙН БҮРЭН СХЕМ & ӨГӨГДӨЛ
-- ==============================================================================
-- Энэхүү SQL файлыг Supabase хяналтын самбарын "SQL Editor" хэсэгт хуулан 
-- "RUN" товч дарж ажиллуулснаар шаардлагатай бүх хүснэгт, RLS бодлого, 
-- болон анхны 20 бүтээгдэхүүний өгөгдөл автоматаар үүснэ.
-- ==============================================================================

-- 1. БҮТЭЭГДЭХҮҮНИЙ ХҮСНЭГТ (PRODUCTS TABLE)
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  sku TEXT NOT NULL UNIQUE,
  price NUMERIC NOT NULL CHECK (price >= 0),
  has_bulk_price BOOLEAN NOT NULL DEFAULT true,
  bulk_price NUMERIC CHECK (bulk_price >= 0),
  bulk_from INTEGER DEFAULT 5 CHECK (bulk_from >= 1),
  category TEXT NOT NULL,
  unit TEXT NOT NULL DEFAULT 'ш',
  status TEXT NOT NULL DEFAULT 'in_stock' CHECK (status IN ('in_stock', 'temporarily_out', 'out_of_stock')),
  stock_count INTEGER NOT NULL DEFAULT 0 CHECK (stock_count >= 0),
  description TEXT,
  badge TEXT,
  color TEXT DEFAULT 'from-teal-400 to-emerald-600',
  image TEXT, -- WebP Data URL эсвэл Supabase Storage линк
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2. АНГИЛЛЫН ХҮСНЭГТ (CATEGORIES TABLE)
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 3. ТОХИРГООНЫ ХҮСНЭГТ (CATALOG SETTINGS TABLE)
CREATE TABLE IF NOT EXISTS public.catalog_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- ИНДЕКСҮҮД (ШУУРХАЙ ХАЙЛТ & ШҮҮЛТ)
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category);
CREATE INDEX IF NOT EXISTS idx_products_status ON public.products(status);
CREATE INDEX IF NOT EXISTS idx_products_sku ON public.products(sku);
CREATE INDEX IF NOT EXISTS idx_categories_sort_order ON public.categories(sort_order);

-- ROW LEVEL SECURITY (RLS) ТОХИРГОО
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalog_settings ENABLE ROW LEVEL SECURITY;

-- Нийт хэрэглэгчид каталог харах эрх (Public Read)
DROP POLICY IF EXISTS "Public can view products" ON public.products;
CREATE POLICY "Public can view products" ON public.products
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public can view categories" ON public.categories;
CREATE POLICY "Public can view categories" ON public.categories
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public can view catalog settings" ON public.catalog_settings;
CREATE POLICY "Public can view catalog settings" ON public.catalog_settings
  FOR SELECT USING (true);

-- Админ удирдлагын эрх (Insert, Update, Delete)
DROP POLICY IF EXISTS "Public full access to products" ON public.products;
CREATE POLICY "Public full access to products" ON public.products
  FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public full access to categories" ON public.categories;
CREATE POLICY "Public full access to categories" ON public.categories
  FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public full access to settings" ON public.catalog_settings;
CREATE POLICY "Public full access to settings" ON public.catalog_settings
  FOR ALL USING (true) WITH CHECK (true);

-- ==============================================================================
-- АНХНЫ ӨГӨГДӨЛ ОРУУЛАХ (INITIAL SEED DATA)
-- ==============================================================================

-- 1. Ангиллууд оруулах
INSERT INTO public.categories (name, sort_order) VALUES
  ('Хүнс, ундаа', 1),
  ('Барилгын материал', 2),
  ('Гоо сайхан', 3),
  ('Цахилгаан бараа', 4),
  ('Авто сэлбэг', 5),
  ('Эмийн сан, эрүүл мэнд', 6),
  ('Гэрийн тэжээвэр амьтан', 7),
  ('Бөөний бэлэн хувцас', 8)
ON CONFLICT (name) DO NOTHING;

-- 2. Каталогийн үндсэн тохиргоо оруулах
INSERT INTO public.catalog_settings (key, value) VALUES
  ('general', '{"showStockCount": true}'::jsonb)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- 3. Бүтээгдэхүүнүүд оруулах (Монгол барааны бодит өгөгдөл)
INSERT INTO public.products (name, sku, price, has_bulk_price, bulk_price, bulk_from, category, unit, status, stock_count, badge, description, color) VALUES
  ('Атар талх (зүссэн, шинэхэн)', 'MN-1001', 2800, true, 2450, 10, 'Хүнс, ундаа', 'ш', 'in_stock', 180, 'Шилдэг борлуулалт', 'Өдөр тутмын хэрэгцээт Атар зүссэн цагаан талх. Бөөнөөр авах дэлгүүр, цайны газарт тохиромжтой.', 'from-amber-400 to-amber-600'),
  ('Өглөө сүү 3.2% 1л (Теч Тетрапак)', 'MN-1002', 4700, true, 4150, 12, 'Хүнс, ундаа', 'ш', 'in_stock', 96, 'Эрэлттэй', 'Үнээний цэвэр ариутгасан өндөр чанартай сүү. 12 ширхэгийн багц хайрцагтай.', 'from-sky-400 to-blue-600'),
  ('Алтан тариа дээд гурил 1кг', 'MN-1003', 3500, false, NULL, NULL, 'Хүнс, ундаа', 'уут', 'in_stock', 240, 'Үндсэн үнэ', 'Монголын шилдэг нэгдүгээр зэргийн цагаан гурил.', 'from-amber-300 to-yellow-600'),
  ('Аянчин байгалийн овьёос 250г', 'MN-1004', 5900, true, 4950, 8, 'Хүнс, ундаа', 'хайрцаг', 'in_stock', 65, 'Эрүүл мэнд', 'Эслэгээр баялаг өглөөний эрүүл хоол.', 'from-emerald-400 to-teal-600'),
  ('Бонаква цэвэр ус 1.5л (6 ширхэгийн багц)', 'MN-1005', 11800, true, 9900, 5, 'Хүнс, ундаа', 'багц', 'in_stock', 75, 'Багцын үнэ', 'Эрдэст цэвэршүүлсэн ундааны цэвэр ус, багцаар нь бөөний үнээр.', 'from-cyan-400 to-blue-500'),
  ('Хаан цай сүүтэй 25ш ууттай', 'MN-1006', 14200, true, 12500, 6, 'Хүнс, ундаа', 'хайрцаг', 'in_stock', 110, 'Онцлох', 'Уламжлалт Монгол хийцтэй сүүтэй хуурай цай.', 'from-orange-400 to-amber-700'),
  ('Эмульс цагаан 25кг (Герман чанар, угаагддаг)', 'BL-2001', 89000, true, 78000, 4, 'Барилгын материал', 'сав', 'in_stock', 32, 'Онцлох чанар', 'Дотор засал, хана таазны өнгөлгөөний дээд зэргийн угаагддаг цагаан эмульс.', 'from-slate-400 to-slate-700'),
  ('Хөтөл Цемент М500 50кг', 'BL-2002', 22000, true, 19800, 20, 'Барилгын материал', 'шуудай', 'in_stock', 180, 'Бөөний үнэ', 'Монгол улсад үйлдвэрлэсэн чанарын баталгаатай барилгын цемент.', 'from-stone-400 to-stone-700'),
  ('Цахилгааны зэс кабель 3x2.5мм² 100м', 'BL-2003', 165000, true, 145000, 3, 'Барилгын материал', 'ороомог', 'in_stock', 22, 'ГОСТ Стандарт', 'Галд тэсвэртэй давхар дулаалгатай 100% цэвэр зэс цахилгааны утас.', 'from-rose-400 to-red-600'),
  ('Lhamour Органик чацарганатай гар хийцийн саван', 'CS-3001', 12500, false, NULL, NULL, 'Гоо сайхан', 'ш', 'in_stock', 85, '100% Эко', 'Монгол чацарганы тосоор баяжуулсан арьс чийгшүүлэгч байгалийн саван.', 'from-amber-400 to-orange-500'),
  ('Goo брэндийн нүүрний чийгшүүлэгч тос 50мл', 'CS-3002', 39000, true, 33500, 6, 'Гоо сайхан', 'ш', 'temporarily_out', 0, 'Шилдэг', 'Хуурай болон эмзэг арьсанд зориулсан байгалийн гаралтай тэжээлийн тос.', 'from-pink-400 to-rose-600'),
  ('Ухаалаг LED гэрэл 12W 10 ширхэгийн багц', 'EL-4001', 45000, true, 38000, 5, 'Цахилгаан бараа', 'багц', 'in_stock', 50, 'Хэмнэлттэй', 'Эрчим хүчний А+ хэмнэлттэй, 25000 цагийн насжилттай цагаан гэрэл.', 'from-yellow-400 to-amber-500'),
  ('Type-C 65W Түргэн цэнэглэгч кабель 2м', 'EL-4002', 22000, true, 17500, 10, 'Цахилгаан бараа', 'ш', 'in_stock', 130, 'Шинэ', 'Бүх төрлийн утас, таблет, нөүтбүүк цэнэглэх бат бөх сүлжмэл кабель.', 'from-indigo-400 to-blue-700'),
  ('Моторын синтетик тос 5W-30 4л (Япон чанар)', 'AP-5001', 125000, true, 108000, 4, 'Авто сэлбэг', 'канистр', 'in_stock', 28, 'Оригинал', 'Өвлийн хүйтэнд хөдөлгүүрийг найдвартай хамгаалах синтетик тос.', 'from-emerald-500 to-teal-800'),
  ('Өвлийн шил арчигч шингэн -35°C 4л', 'AP-5002', 13500, false, NULL, NULL, 'Авто сэлбэг', 'сав', 'out_of_stock', 0, 'Өвлийн эрэлт', 'Хөлдөхгүй, шил зурахгүй дээд зэргийн өвлийн шингэн.', 'from-blue-400 to-cyan-700'),
  ('Витамин С 1000мг хөөсөрдөг үрэл 20ш', 'PH-6001', 19500, true, 16500, 8, 'Эмийн сан, эрүүл мэнд', 'хайрцаг', 'in_stock', 65, 'Дархлаа', 'Дархлаа сэргээх, ядаргаа тайлах өндөр тунтай витамин С.', 'from-orange-400 to-red-500'),
  ('3 давхаргат эмнэлгийн маск 50ш хайрцагтай', 'PH-6002', 9900, true, 7900, 10, 'Эмийн сан, эрүүл мэнд', 'хайрцаг', 'in_stock', 140, 'Бөөний үнэ', 'Бактери шүүгчтэй, зөөлөн чихэвчтэй ариутгасан маск.', 'from-sky-300 to-teal-500'),
  ('Нохойн шим тэжээлт хуурай хоол 3кг', 'PT-7001', 48000, true, 41000, 5, 'Гэрийн тэжээвэр амьтан', 'уут', 'in_stock', 35, 'Премиум', 'Үхрийн мах, ногоотой бүх насны нохойд зориулсан тэжээллэг хоол.', 'from-amber-500 to-stone-600'),
  ('Хөвөн даавуун подволк 10ш багц (S-XXL сонголт)', 'FS-8001', 190000, true, 160000, 3, 'Бөөний бэлэн хувцас', 'багц', 'in_stock', 20, '100% Хөвөн', 'Бөөний худалдаа, хэвлэл болон ажлын хувцсанд зориулсан чанартай подволк.', 'from-violet-400 to-purple-700'),
  ('Өвлийн дулаан ноосон оймс 20 хос', 'FS-8002', 95000, true, 79000, 4, 'Бөөний бэлэн хувцас', 'багц', 'temporarily_out', 0, 'Дулаан', 'Тэмээний ноосны орцтой, хасах хэмд дулаанаа найдвартай барих өвлийн оймс.', 'from-yellow-600 to-amber-900')
ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  price = EXCLUDED.price,
  has_bulk_price = EXCLUDED.has_bulk_price,
  bulk_price = EXCLUDED.bulk_price,
  bulk_from = EXCLUDED.bulk_from,
  category = EXCLUDED.category,
  unit = EXCLUDED.unit,
  status = EXCLUDED.status,
  stock_count = EXCLUDED.stock_count,
  badge = EXCLUDED.badge,
  description = EXCLUDED.description,
  color = EXCLUDED.color,
  updated_at = timezone('utc'::text, now());
